id: P563AF536
initial_creation_type: ocr
source_metadata:
  volumes:
    ccff4d437b44450782b2b9f3ccce3be8:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཕགས་པ་འཇམ་པའི་དབྱངས་ཀྱི་བསྟོད་པ།
      total_pages: 1379
      volume_number: 37
